version: '3.8'

services:
  mono-map-api:
    image:  djm75913/mono_map_api:latest
    container_name: mono-map-api
    ports:
      - "3001:3000"
    environment:
      MONGO_URL: ${MONGO_URL_DOCKER}
      PORT: ${PORT}
      MAIL_SECRET_KEY: ${MAIL_SECRET_KEY}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAIL_USER: ${MAIL_USER}
      MAIL_TO: ${MAIL_TO}
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: